
export const projectsData = [
    {
        id: 1,
        name: "Home Connect App",
        description: "Mobile App that connects homeless people with shelters.",
        type: "Development",
        year: "2023",
        color: "#FFD700",
        image: "https://i.imgur.com/Eyl7LMI.png",
        link: "https://github.com/pawanbhayde/homeconnect",
    },
    {
        id: 2,
        name: "Fluttercn Website",
        description: "Shadcn/ui based flutter components library.",
        type: "Development",
        year: "2024",
        color: "#FFD700",
        image: "https://i.imgur.com/v21WpsS.png",
        link: "https://github.com/pawanbhayde/fluttercn",
    },
    {
        id: 3,
        name: "Amime Hub App",
        description: "Mobile App for anime lovers.",
        type: "Development",
        year: "2024",
        color: "#FFD700",
        image: "https://i.imgur.com/faFlduI.png",
        link: "https://github.com/pawanbhayde/animeapp",
    },
    {
        id: 4,
        name: "Smart Bike App",
        description: "UIUX case study for a Smart Bike app.",
        type: "Design",
        year: "2024",
        color: "#FFD700",
        image: "https://i.imgur.com/UCuxpAL.png",
        link: "https://www.behance.net/gallery/197925617/Smart-Bike-Mobile-App",
    },
    {
        id: 5,
        name: "Zeelaundry App",
        description: "UIUX case study for a laundry app.",
        type: "Design",
        year: "2023",
        color: "#FFD700",
        image: "https://i.imgur.com/lpIGw5D.png",
        link: "https://www.behance.net/gallery/177110899/ZeeLaundry-Best-laundry-and-ironing-services",
    },
    {
        id: 6,
        name: "Kolkatta Veg Roll's",
        description: "Social Media post for a local food joint.",
        type: "Graphic Design",
        year: "2024",
        color: "#FFD700",
        image: "https://i.imgur.com/7sNwtxv.png",
        link: "https://www.behance.net/gallery/197522465/Social-Media-Post-Kolkatta-veg-rolls",
    },
];